<pre class="pre-text policy-restrict"><div><span>Terms of Use – For User</span></div>

This document is an electronic record in terms of the Information Technology Act, 2000 and the rules framed thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the  website (www.wowrol.com).

wowrol internet private limited.&rlm; is a company incorporated under the laws of The Republic of india with its registered office at PLOT NO 28 PARSHAV NATH ENCLAVE,KUNHADI KOTA (RAJASTHAN) 324008 (hereinafter referred to as “<i>We</i>”, “<i>Us</i>”, “<i>Wowrol </i>” or “<i>Our</i>”, which expression shall mean and include its affiliates, successors and permitted). Wowrol  provides its Services to You subject to the notices, terms and conditions as set forth in these Terms of Use.

The domain name <i>www.wowrol.com</i> (hereinafter referred to as the “Website”) is owned by Wowrol . Your use of the Website and the Services are governed by the following terms and conditions (hereinafter referred to as the “Terms of Use”) as applicable to the Website including the applicable policies which are incorporated herein by way of reference. For the purpose of these Terms of Use, wherever the context so requires “You”, “Registered User” or “Your” shall mean and refer to any natural or legal person who has agreed to become a registered user on the Website by providing registration data while registering on the Website as a registered user availing the Services provided by Us through the Website. The term “Account” as referred to in these Terms of Use shall mean and include the Account held by You with Wowrol  (administered by a password) on the Website for using the Services.

You acknowledge and agree that You shall be subject to the policies that are applicable to the Website and by mere use of the Website, You shall be legally contracting with Wowrol  and these Terms of Use including the policies constitute Your binding obligations with Wowrol . When You use any of the Services provided by Us through the Website, You will be subject to the rules, guidelines, policies, terms, and conditions applicable to the Services, and the same shall be deemed to be incorporated into this Terms of Use and be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.

ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE INDICATES YOUR ACCEPTANCE OF ALL THE TERMS AND CONDITIONS IN THESE TERMS OF USE. PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE PROCEEDING. YOU DECLARE YOUR ACCEPTANCE TO ABIDE AND BE BOUND BY THESE TERMS OF USE BY CHECKING THE “I HAVE READ AND ACCEPTED THE TERMS OF USE” BOX AT THE TIME OF CREATING THE ACCOUNT. IF YOU DO NOT AGREE WITH THE TERMS OF USE, PLEASE DO NOT USE THIS WEBSITE.

These Terms of Use will be effective immediately upon Your acceptance of Our terms and conditions, the creation of Your Account on Our Website being indicative of such acceptance. These Terms of Use shall be enforceable against You in the same manner as any other written agreement.

<span>1.Services</span>

We provide a platform through which the new and growing businesses like, You can interact with other users for the purpose of structuring and evaluating business ideas, assessing a potential business relationship and through such platform, facilitating the validation of the business ideas provided by the businesses as well as effective and secure communication between such businesses and other users (“Services”). We also provide certain offline services including but not limited to, conducting seminars, workshops for You and providing You with an opportunity to interact with other users of the Website offline.

If You wish to subscribe to Our newsletter(s) or receive notifications or e-mails from Us, We will use Your name and latest e-mail address provided by You in this regard.&nbsp;However, You may choose to stop receiving Our newsletters by following the instructions to unsubscribe as included in these e-mails or You can contact Us at&nbsp;contact@Wowrol .com

<span>2.Account</span>

Prior to using the Website or any part of the Services, You shall be required to register with Wowrol  through the Website by setting up an Account and selecting a desired password and user ID. 

You agree that at the time of creating Your Account, You will not:

<ol type="i">
  <li>Select or use as an user ID the name of another person;</li>
  <li>Use as a user ID, a name that is otherwise offensive, vulgar or obscene.</li>
</ol>
We reserve the right to refuse registration of, or cancel an user ID and password at Our sole discretion. You are solely responsible for any and all activity that takes place on Your Account and for maintaining the confidentiality of Your Account details. You may never use another registered user’s account without obtaining the prior written consent of such other registered user. In the event that You discover any unauthorized use of Your Account or other Account-related security breach, You must immediately notify Us in writing of such unauthorized use.

During the process of registration, You may be prompted with registration forms on the Website or You may be asked to provide documentation necessary to complete the registration process. By initiating the process of registration with Wowrol , You agree to:

<ol type="i">
  <li>Provide accurate, complete, and updated registration information;</li>
  <li>Maintain the security of Your password and identification;</li>
  <li>Maintain and promptly update Your registration information and any other information that You provide to Us;</li>
  <li>Ensure, at all times, the accuracy, currency and completeness of such information;</li>
  and
  <li>Accept all risks of unauthorized access to and use of Your Account and related information as well as any other
    information You provide to Us.
  </li>
</ol>
Failure to submit the required registration information to Us within such time period as prescribed by Us will constitute a breach of these Terms of Use, which may result in immediate termination of Your Account.

If You provide any information that is untrue, inaccurate, not current or incomplete, We have the right, at Our sole discretion, to suspend or terminate Your Account and to refuse any and all current or future use of the Services and / or the Website (or any portion thereof). We shall use and protect Your proprietary information in accordance with the terms of Our Privacy Policy incorporated into these Terms of Use by reference.

In order to reduce the risk of unauthorized access, all accounts maintained with Us through the Website are locked after five (5) consecutive incorrect login attempts. In the event of such lockout, You can email the administrator at contact@Wowrol .com and the Account shall be unlocked upon receipt of Your email. You can also request for a password reset on our website through the ‘forgot password’ option on the website.


You may be required to upload certain information about Your business plan, including information that may be reasonably considered to be confidential, and to designate which users may have access to that information. We will make best efforts to ensure that only such users identified by You have access to the said information. However, We have no control and assume no responsibility arising out of any user’s viewing / using/ distributing such information.

You may decline to submit certain information through the Website, in which case You may not be allowed to access certain features / parts of the Website.

Further, You can choose to de-activate Your Account with Wowrol  maintained on the Website. However, in the event subscription to Our Website is pre-paid, any cancellation of Your Account will be made effective only on the last day of Your payment term. In the event You de-activate Your Account with Wowrol , these Terms of Use, as applicable to You, will be deemed to have been terminated save and except such obligations that shall by their nature or specific mention herein, survive the termination of these Terms of Use. You acknowledge and agree that notwithstanding Your de-activating the Account, Wowrol  shall have the right to store and maintain all information provided by You as part of its records for such time and for such purposes as permitted or may be required under any applicable law for the time being in force.

<span>3.Subscription</span>

Subscription to Our Website shall be in accordance with the business model displayed on the Website. Usage of Our Website and Services shall be based on a non-refundable pricing model. Pricing shall be determined based upon Your choice of subscription level from the different subscription levels made available on the Website. In consideration for the Services rendered by Wowrol , You agree to pay the applicable subscription fees at the time of registration on the Website.This subscription fee shall be subject to applicable taxes. In the event of late payment for subscriptions, Wowrol  will send You a notice thereof to Your e-mail address on record, and Your access to the Services will be temporarily disabled until payment therefor is received.

<span>4.Intellectual Property</span>

This Website is operated by and is the sole property of Wowrol . Any and all material on this Website, including images, illustrations, audio and video clips are protected by copyrights, trademarks, and other intellectual property rights that are owned by Us or by other parties that have licensed such material to Us or such parties having ownership of content uploaded on the Website. You agree that any and all material displayed on the Website is solely for Your personal use and You shall not, whether directly or indirectly, copy, reproduce, republish, post, upload, transmit or distribute such material in any manner and through any media including by way of e-mail or other electronic means and You shall not assist any other person in doing so. Modification of the said materials or use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal use is a violation of the said copyrights, trademarks and other intellectual proprietary rights, and is expressly prohibited. Unless otherwise specified, when any content is downloaded to Your computer, You do not obtain any ownership interest in such content or any use of the content for any other purpose. We reserve all rights not expressly granted to You.

Wowrol  shall have no obligation to monitor or enforce any intellectual property rights that may be associated with the content provided by You on the Website.

<span>5.Intended Use</span>

This Website is intended for use by new and growing businesses like, You who are desirous of interacting with other users for such purposes including but not limited to structuring and evaluating business ideas, assessing a potential business relationship and through such platform, getting the business ideas validated. All information provided on this Website or any other website hyperlinked to this Website shall be used solely for and in furtherance of the said purpose.

<span>6.Prohibited Uses</span>

The Website may be used only for lawful purposes. Wowrol  specifically prohibits any use of the Website for, and You further agree not to use the Website for, any of the following purposes:

<ol type="i">
  <li>Modifying, publishing, transmitting, distributing, displaying, performing, participating in the transfer or sale
    of, create derivative works on, or in any way exploiting, any of the copyrighted material contained on the Website,
    in whole or in part, without Our prior written consent;
  </li>
  <li>Sub-leasing, leasing, selling, assigning, transferring, distributing, renting, permitting concurrent use of, or
    granting other rights in the Services and any material and documentation provided on the Website to any third party;
  </li>
  or
  <li>Providing use of the Services in a computer service business, network, time sharing, interactive cable television,
    multiple CPU or multiple or concurrent user arrangement to users who are not individually licensed by Wowrol  or
    otherwise exploiting any portion of, the use of or access to the Services or the materials or documentation provided
    on the Website in contravention of these Terms of Use.
  </li>
</ol>
<span>7.Modifications</span>

We reserve the right at any time and from time to time, in Our sole discretion, to modify or discontinue, temporarily or permanently, the Services or any part thereof, including the transmission of any related materials or documentation, with or without providing prior notice to You. We further reserve the right at any time and from time to time, at Our sole discretion, to alter, modify or terminate any content or features contained on the Website without providing to You prior notice of such alteration, modification or termination. You agree that Wowrol  shall not be liable to You or to any third party claiming through You, for any modification, suspension, or discontinuance of the Services, content, or features provided on the Website.

<span>8.System Limitations and Failures</span>

We use internally developed systems for providing the Services to You. These systems may encounter technical or other limitations, and computer and communications hardware systems might experience interruptions. Further, We continually enhance and improve these systems in order to accommodate the level of use of the Website. We may also add additional features and functionality to the Services that might result in the need to develop or license additional technologies. Increased utilization of the Website or providing new features or functionality may cause unanticipated system disruptions, slower response times, degradation in levels of customer service, and delays in reporting accurate financial information. You agree that We shall not be liable to You or to any third party claiming through You, for any such failures contemplated herein.

<span>9.Privacy and Confidentiality</span>

Your use of the Website is governed by Our Privacy Policy, which can be located at http://www.wowrol.com/Privacy.

Please read Our Privacy Policy to understand Our information collection and usage practices. You may obtain certain confidential information, including without limitation, technical, contractual, product, pricing and other valuable information that should reasonably be understood as confidential (“Confidential Information”). You acknowledge and agree to hold all Confidential Information in strict confidence. Title and all interests to all Confidential Information shall be vested in Us. Your obligations regarding Confidential Information will survive the termination of these Terms of Use in accordance with Clause 13 below. Upon such termination, You must stop forthwith using any Confidential Information to which You may have been exposed in due course of Your use of the Services.

You agree that Your obligations under this Clause 9 are necessary and reasonable in order to protect Our business and expressly agree that monetary damages would be inadequate to compensate for any breach of any covenant or agreement set forth herein.  Accordingly, You agree and acknowledge that any such violation or threatened violation will cause irreparable harm and injury to Wowrol  and that, in addition to any other remedies that may be available, in law, equity or otherwise, Wowrol  shall be entitled to obtain injunctive relief against the threatened breach of the terms of this Clause or the continuation of any such breach.

<span>10.Links to / from other Websites</span>

The Website may contain link/s to various other websites. These links are provided solely for Your convenience and benefit. Wherever such link/s lead to websites which are not owned by or belong to Wowrol , We shall not be responsible for the content, products and services provided on such linked sites. We do not warrant or make any representations regarding the correctness or accuracy of the content on such websites. If You decide to access such linked websites, You do so at Your own risk. We do not in any way endorse the linked websites.

Similarly, this Website can be made accessible through a link created by other websites. Access to this Website through such link/s shall not mean or be deemed to mean that the objectives, aims, purposes, ideas, concepts of such other websites or their aim or purpose in establishing such link/s to this Website are necessarily the same or similar to the idea, concept, aim or purpose of Our Website or that such links have been authorized by Us. We are not responsible for any representation/s of such other websites while affording such link and no liability can arise upon Wowrol  consequent to such representation, its correctness or accuracy. In the event that any link/s afforded by any other website/s derogatory in nature to the objectives, aims, purposes, ideas and concepts of this Website, is utilized to visit this Website and such event is brought to the notice or is within the knowledge of Wowrol , civil or criminal remedies as may be appropriate shall be invoked.

<span>11.Security</span>

You are prohibited from violating or attempting to violate the security of the Website, including, without limitation:

<ol type="i">
  <li>Accessing data not intended for You or logging into an account which You are not authorized to access;</li>
  <li>Attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication
    measures without proper authorization;
  </li>
  or
  <li>Attempting to interfere with service to any user, host, or network.</li>
</ol>
You shall not misuse this Website by knowingly introducing viruses, trojans, worms, logic bombs or other materials that are malicious or technologically harmful (hereinafter referred together as “Viruses”). You must not attempt to gain unauthorized access to Our Website, the server on which the Website is stored or any server, computer or database connected to this Website. You must not attack this Website via a denial-of-service attack.

By breaching the provisions of this Clause 11, You may be liable to be prosecuted under the Information Technology Act, 2000 or other applicable law. We will report any such breach to the relevant law enforcement authorities and we will co-operate with such authorities by disclosing Your identity to them. In the event of such a breach, Your rights to use this Website will cease immediately.

We will not be liable for any loss or damage caused by a denial-of-service attack or Viruses that may infect Your computer equipment, computer programs, data or other proprietary material due to Your use of this Website or to your downloading of any material posted on it, or on any website linked to it.

You agree to immediately report to Us all incidents involving suspected or actual unauthorized access, disclosure, alteration, loss, damage, or destruction of data.

<span>12.Monitoring</span>

All electronic communications and content presented and / or passed to Us, including that presented and / or passed from remote access connections, may be monitored saved, read, transcribed, stored, or retransmitted in the course of daily operations by any duly authorized employee or agent of Wowrol  in the exercise of their duties, or by law enforcement authorities who may be assisting Wowrol  in investigating possible contravention / non-compliance with applicable law. Electronic communications and content may be examined by automated means. Further, Wowrol  has the right to reject, at its sole discretion, from the Website any electronic communications or content deemed not to be in compliance with the corporate policies and procedures of Wowrol .

<span>13.Termination</span>

In the event it is determined by Us that You have violated any of these Terms of Use, We shall have the right, at Our sole discretion, to suspend or terminate Your Account and prohibit access to the Services and the Website forthwith. Any such suspension or termination of access to the Services and the Website, and any deletion of Account information, may be effected by Us without providing You with a prior written notice in this regard. Upon such termination of access to the Services and the Website, these Terms of Use, as applicable to You, will be deemed to have been terminated.

Further, these Terms of Use, as applicable to You, will be deemed to have been terminated in the event of You de-activate Your Account in accordance with Clause 2 of these Terms of Use.

You acknowledge and agree that, upon termination, You shall immediately destroy any copies made of any portion of the content contained on the Website. You acknowledge and agree that Wowrol  shall not be liable to You or any third party claiming through You, for any suspension or termination of access to the Services and the Website or for any deletion of Account information.

<span>14.Disclaimer of Warranties and Limitation of Liability</span>

The Website, including any content or information contained on it in connection with the Services, is provided on an “as is” basis. We hereby expressly disclaim all warranties and representations of any kind with respect to the Services or content contained on the Website, including but not limited to

<ol type="i">
  <li>Warranties as to merchantability or use for a particular purpose whether or not Wowrol  knows or has reason to
    know or has been advised of any such purpose,
  </li>
  or
  <li>Warranties as to any results to be obtained from any use of the Services or Wowrol  content or information
    derived from the Services.
  </li>
</ol>
Wowrol  is not a placement agent for any securities. Wowrol  content, including the Services, shall not be construed as investment advice by Wowrol  or an opinion provided by Wowrol  regarding the appropriateness or suitability of any investment, or a recommendation or an offer or solicitation by Wowrol  or the new and growing businesses for the purchase or sale of any security or securities in general, nor otherwise an endorsement, inducement, or solicitation of any type. Wowrol  shall have no liability for investment decisions based upon, or the results obtained from Wowrol  content, including the Services. Wowrol  content is intended for general information purposes only and should not be relied or acted on without obtaining business and/or legal advice.

You acknowledge and agree that by the mere fact of registering with the Website, You shall not have the right to be entitled to any investment from a potential investor on the Website. Such right to seek investment shall be conferred upon You only in the event that You extend an express invitation or offer to the potential investor pursuant to which such offer is accepted by the investor.

Nothing contained herein is intended to aid in or form the sole basis of any investment decision. You are expected to conduct a comprehensive due diligence review concerning a particular investment.

Wowrol  does not endorse or act on behalf of any third party. In the event You engage the services of / interact with any third party, through the Website, Wowrol  will not be liable to You for any act or omission by such third party in relation thereto.

Wowrol  shall have no liability for any losses, special, punitive, incidental, direct or indirect, in contract, tort, or otherwise, incurred in connection with the Services or Wowrol  content, including but not limited to loss of revenue or profit or any other commercial or economic loss or for any decision made or action taken by any third party in reliance upon the Services or Wowrol  content.

You agree to indemnify and hold Wowrol  harmless from any claim or demand, including reasonable attorney's fees and expenses, made by any third party due to or arising out of Your use of the Website, the violation of the terms of this Terms of Use by You, or Your unauthorized use of any other registered user’s account or Your infringement of any intellectual property or other right of any person or entity, or as a result of any threatening, libelous, obscene, harassing or offensive material posted / transmitted by You on the Website .

Your obligations under this Clause 14 shall survive the termination of these Terms of Use in accordance with Clause 13 above.

<span>15.Foreign Jurisdictions</span>

Wowrol  makes no representation that the content contained on the Website is appropriate or to be used or accessed outside of the Republic of Singapore. If You use or access the Website from outside the Republic of Singapore, You do so at Your own risk and are responsible for compliance with the laws of such jurisdiction.

<span>16.Governing Law and Dispute Resolution</span>

These Terms of Use shall be governed by and construed in accordance with the laws of the Republic of Singapore and subject to the provisions of arbitration set out herein, the courts at Singapore shall have exclusive jurisdiction in relation to any disputes arising out of or in connection with these Terms of Use.

If any dispute arises between Wowrol  and the Registered User during the subsistence of these Terms of Use or thereafter, in connection with or arising out of the validity, interpretation, implementation or alleged breach of any provision of these Terms of Use or regarding a question, such dispute shall be referred to and finally resolved by arbitration under the laws of The Republic of Singapore.

There shall be one (1) arbitrator and the venue of arbitration shall be Singapore.

The language of the arbitration proceedings and of all written decisions and correspondence relating to the arbitration shall be English.

<span>17.Severability</span>

If any term, provision, covenant or restriction of these Terms of Use is held by a court of competent jurisdiction to be invalid, void or unenforceable, the remainder of the terms, provisions, covenants and restrictions of these Terms of Use shall remain in full force and effect and shall in no way be affected, impaired or invalidated.

<span>18.No Waiver</span>

The rights and remedies available under this Terms of Use may be exercised as often as necessary and are cumulative and not exclusive of rights or remedies provided by law. It may be waived only in writing. Delay in exercising or non-exercise of any such right or remedy does not constitute a waiver of that right or remedy, or any other right or remedy.

<span>19.General</span>

These Terms of Use comprise the full and complete agreement between the You and Wowrol  with respect to the use of the Services and the Website and supersedes and cancels all prior communications, understandings and agreements between You and Wowrol , whether written or oral, expressed or implied with respect thereto.

<span>20.Contact</span>

Please address any questions You may have about the Terms of Use associated with the Website by writing to Us at: <i>contact@Wowrol .com</i>

</pre>