<?php
    




$shippingLable='<div class="block _bdy _B-gray bg_0 m_b10" style="box-sizing: border-box; margin: 30px auto; padding: 5px; border: 1px solid rgb(216, 216, 216); vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; min-height: 1px; max-width: 1000px; background-color: rgb(255, 255, 255) !important;">
	<div class="block  bg_0 " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%;">
		<div class="block ul _bdy_5-0 ov-hi bg_0" data-role="cart-card" style="box-sizing: border-box; margin: 0px; padding: 5px 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%; overflow: hidden; position: relative; list-style: none;">
			<div class="block li m_b5" style="box-sizing: border-box; margin: 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%; position: relative;">
				<div class="w9" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-variant-ligatures: normal; font-stretch: inherit; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Roboto, &quot;Segoe UI&quot;, Calibri, sans-serif; float: left; position: relative; min-height: 1px; width: 100%; color: rgb(41, 47, 51); orphans: 2; widows: 2;">
					<div>
						<span class=" fw-b m0" style="box-sizing: border-box; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: inherit; font-family: inherit; margin: 0px !important;">
							<div class="block w4 col4  " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-variant-ligatures: normal; font-weight: normal; font-stretch: inherit; line-height: inherit; min-height: 1px; width: 100%; float: left; position: relative;">
								<div class="block _bdy fg_5 ff_3" style="box-sizing: border-box; margin: 0px; padding: 5px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, Calibri, Arial, sans-serif; min-height: 1px; width: 100%; color: rgb(51, 51, 51) !important;">
									<h4 style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; line-height: 1;">Shipping Address</h4>
									<div class="block" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%;">
										<div class="block " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%">
											<ul class="ul block ct" style="box-sizing: border-box; margin: 0.25em 0px 0.5em; padding: 0px; border: 0px; vertical-align: baseline; font-stretch: normal; font-family: Arial, Helvetica, sans-serif; min-height: 1px; width: 100%; word-wrap: break-word; word-break: break-word; position: relative; list-style: none;">
												<li class="li" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; position: relative; display: block;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">{{{LableName}}}</span></li>
												<li class="li" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; position: relative; display: block;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">{{{addr.address}}}</span></li>
												<li class="li" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; position: relative; display: block;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">{{addr.location_name}},{{addr.Districtname}} {{addr.Statename}} {{addr.Country}} {{addr.pincode}} </span></li>
												<li class="li" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; position: relative; display: block;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">{{addr.Country}}</span></li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<div class="block w4 col4 " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-variant-ligatures: normal; font-weight: normal; font-stretch: inherit; line-height: inherit; min-height: 1px; width: 100%; float: left; position: relative;">
								<div class="block  bg_0 m_b5" style="box-sizing: border-box; margin: 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%;">
									<div class=" block _bdy al-l ff-2  " style="box-sizing: border-box; margin: 0px; padding: 5px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%;"><span class="tt-u " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; text-transform: uppercase;">PAYMENT METHOD</span><span class="fw-b span" style="box-sizing: border-box; margin: 0px 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: inherit; font-family: inherit; display: inline-block;">Cash on Delivery (COD)</span></div>
								</div>
								<div class="block  bg_0 m_b5" style="box-sizing: border-box; margin: 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%;">
									<div class=" block _bdy al-l ff-2 " style="box-sizing: border-box; margin: 0px; padding: 5px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%;"><span class="tt-u " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; text-transform: uppercase;">SHIPPING METHOD</span><span class="fw-b span" style="box-sizing: border-box; margin: 0px 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: inherit; font-family: inherit; display: inline-block;">{{{shippingMethode}}}</span></div>
								</div>
							</div>
							<div class="block w4 col4  " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-variant-ligatures: normal; font-weight: normal; font-stretch: inherit; line-height: inherit; min-height: 1px; width: 100%; float: left; position: relative;">
								<div class="block _bdy" style="box-sizing: border-box; margin: 0px; padding: 5px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 100%;">
									<div class="block" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 450px;">
										<div class="w8 left b_grl al-r" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(216, 216, 216); border-bottom-color: initial; border-left-color: initial; border-image-source: initial; border-image-slice: initial; border-image-width: initial; border-image-outset: initial; border-image-repeat: initial; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 299.969px; text-align: right !important;"><span class="" style="box-sizing: border-box; margin: 0px 10px 0px 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">Sub Total</span></div>
										<div class="w4 left " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 149.984px;">
											<div class="block m_b5 al-r  " style="box-sizing: border-box; margin: 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 149.984px; text-align: right !important;"><span class=" m0" style="box-sizing: border-box; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; margin: 0px !important;">{{currency}} {{sub_total}}</span></div>
										</div>
									</div>
									<div class="block" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 450px;">
										<div class="w8 left b_grl al-r" style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(216, 216, 216); border-bottom-color: initial; border-left-color: initial; border-image-source: initial; border-image-slice: initial; border-image-width: initial; border-image-outset: initial; border-image-repeat: initial; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 299.969px; text-align: right !important;"><span class="" style="box-sizing: border-box; margin: 0px 10px 0px 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">Shipping</span></div>
										<div class="w4 left " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 149.984px;">
											<div class="block m_b5 al-r  " style="box-sizing: border-box; margin: 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 149.984px; text-align: right !important;"><span class=" m0" style="box-sizing: border-box; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; margin: 0px !important;">{{currency}} {{totalshipping}}</span></div>
										</div>
									</div>
									<div class="block " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 450px;">
										<div class="w8 left b_grl al-r " style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(216, 216, 216); border-bottom-color: initial; border-left-color: initial; border-image-source: initial; border-image-slice: initial; border-image-width: initial; border-image-outset: initial; border-image-repeat: initial; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 299.969px; text-align: right !important;"><span class="" style="box-sizing: border-box; margin: 0px 10px 0px 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">Total</span></div>
										<div class="w4 left " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 149.984px;">
											<div class="block m_b5 al-r " style="box-sizing: border-box; margin: 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 149.984px; text-align: right !important;"><span class=" m0" style="box-sizing: border-box; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; margin: 0px !important;">{{currency}} {{ total}}</span></div>
										</div>
									</div>
									<div class="block fw-b" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 450px;">
										<div class="w8 left b_grl al-r " style="box-sizing: border-box; margin: 0px; padding: 0px; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(216, 216, 216); border-bottom-color: initial; border-left-color: initial; border-image-source: initial; border-image-slice: initial; border-image-width: initial; border-image-outset: initial; border-image-repeat: initial; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 299.969px; text-align: right !important;"><span class="" style="box-sizing: border-box; margin: 0px 10px 0px 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit;">Grand Total:</span></div>
										<div class="w4 left " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; float: left; position: relative; min-height: 1px; width: 149.984px;">
											<div class="block m_b5 al-r " style="box-sizing: border-box; margin: 0px 0px 5px; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; min-height: 1px; width: 149.984px; text-align: right !important;"><span class=" m0" style="box-sizing: border-box; padding: 0px; border: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; margin: 0px !important;">{{currency}} {{ total}}</span></div>
										</div>
									</div>
								</div>
							</div>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>';



$Template=$shippingLable;

?>